In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# **Introduction to Tensorflow** 

In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # 0 = all logs, 1 = filter INFO, 2 = filter WARNING, 3 = filter ERROR
import tensorflow as tf


scalar = tf.constant(5)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

E0000 00:00:1754044058.864200      13 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1754044058.937374      13 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [3]:
variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

In [4]:
random_tensor = tf.random.uniform(shape=(2, 3), minval=0, maxval=10, dtype=tf.int32)

In [5]:
import tensorflow as tf

matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Tensor:\n", matrix)
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)
print("Rank:", tf.rank(matrix).numpy())

Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Data Type: <dtype: 'int32'>
Rank: 2


In [6]:
tensor = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
]) 

new_shape = (4, 2)  

reshaped = tf.reshape(tensor, new_shape)
expanded = tf.expand_dims(tensor, axis=0)
squeezed = tf.squeeze(expanded, axis=0)  # Using 'expanded' here since original tensor wasn't actually squeezed
transposed = tf.transpose(tensor, perm=[1, 0, 2])  # Swap first two axes

print("Original shape:", tensor.shape)
print("Reshaped:", reshaped.shape)
print("Expanded:", expanded.shape)
print("Squeezed:", squeezed.shape)
print("Transposed:", transposed.shape)


Original shape: (2, 2, 2)
Reshaped: (4, 2)
Expanded: (1, 2, 2, 2)
Squeezed: (2, 2, 2)
Transposed: (2, 2, 2)


In [7]:
import tensorflow as tf

float_tensor = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
bool_tensor = tf.constant([True, False, True], dtype=tf.bool)

In [8]:
casted_tensor = tf.cast(float_tensor, dtype=tf.int32)

In [9]:
import tensorflow as tf

# Creating a 3-D tensor (batch of 2 images, 3x3 pixels, 1 channel)
tensor = tf.constant([
    [[[255], [0], [127]],
     [[255], [0], [127]],
     [[255], [0], [127]]],
    
    [[[255], [0], [127]],
     [[255], [0], [127]],
     [[255], [0], [127]]]
], dtype=tf.uint8)

print("Tensor:\n", tensor)
print("Shape:", tensor.shape)
print("Data Type:", tensor.dtype)
print("Rank:", tf.rank(tensor).numpy())

# Reshaping the tensor to flatten the images
reshaped_tensor = tf.reshape(tensor, (2, 9))
print("Reshaped Tensor:\n", reshaped_tensor)
print("New Shape:", reshaped_tensor.shape)

Tensor:
 tf.Tensor(
[[[[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]]


 [[[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]

  [[255]
   [  0]
   [127]]]], shape=(2, 3, 3, 1), dtype=uint8)
Shape: (2, 3, 3, 1)
Data Type: <dtype: 'uint8'>
Rank: 4
Reshaped Tensor:
 tf.Tensor(
[[255   0 127 255   0 127 255   0 127]
 [255   0 127 255   0 127 255   0 127]], shape=(2, 9), dtype=uint8)
New Shape: (2, 9)


# **Understanding Tensors**

In [10]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = tf.add(a, b)
print(c)  

c = tf.subtract(a, b)
print(c)  

c = tf.multiply(a, b)
print(c)  

c = tf.divide(b, a)
print(c) 

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64)


In [11]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
product = tf.matmul(matrix1, matrix2)
print(product)

transposed = tf.transpose(matrix1)
print(transposed)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [12]:
import tensorflow as tf

tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Original Shape:", tensor.shape)  

reshaped = tf.reshape(tensor, (3, 2))
print("Reshaped Tensor:\n", reshaped)
print("New Shape:", reshaped.shape)  

Original Shape: (2, 3)
Reshaped Tensor:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
New Shape: (3, 2)


In [13]:
tensor = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

sliced = tensor[:2]
print("Sliced Tensor:\n", sliced)

element = tensor[1, 1, 1]
print("Specific Element:", element) #output=8

Sliced Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Specific Element: tf.Tensor(8, shape=(), dtype=int32)


In [14]:
# Tensor A of shape (3, 1)
A = tf.constant([[1], [2], [3]])

# Tensor B of shape (1, 4)
B = tf.constant([[10, 20, 30, 40]])

# Broadcasting to shape (3, 4)
C = A + B
print("Broadcasted Tensor:\n", C)

Broadcasted Tensor:
 tf.Tensor(
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]], shape=(3, 4), dtype=int32)


In [15]:
tensor = tf.constant([[1, 2], [3, 4]])
sum_all = tf.reduce_sum(tensor)
sum_axis0 = tf.reduce_sum(tensor, axis=0)
sum_axis1 = tf.reduce_sum(tensor, axis=1)
print("Sum All:", sum_all)           # 10
print("Sum Axis 0:", sum_axis0)     # [4, 6]
print("Sum Axis 1:", sum_axis1)     # [3, 7]

mean_all = tf.reduce_mean(tensor)
print("Mean All:", mean_all)  

max_all = tf.reduce_max(tensor)
print("Max All:", max_all)  

Sum All: tf.Tensor(10, shape=(), dtype=int32)
Sum Axis 0: tf.Tensor([4 6], shape=(2,), dtype=int32)
Sum Axis 1: tf.Tensor([3 7], shape=(2,), dtype=int32)
Mean All: tf.Tensor(2, shape=(), dtype=int32)
Max All: tf.Tensor(4, shape=(), dtype=int32)


In [16]:
# Original tensor of shape (2, 3)
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Adding a new axis to make it (2, 3, 1)
expanded = tf.expand_dims(tensor, axis=-1)
print("Expanded Tensor Shape:", expanded.shape)  # (2, 3, 1)

# Removing the added axis
squeezed = tf.squeeze(expanded, axis=-1)
print("Squeezed Tensor Shape:", squeezed.shape)  # (2, 3)

Expanded Tensor Shape: (2, 3, 1)
Squeezed Tensor Shape: (2, 3)


In [17]:
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Concatenate along axis 0
concat_axis0 = tf.concat([tensor1, tensor2], axis=0)
print("Concatenated along axis 0:\n", concat_axis0)

# Concatenate along axis 1
concat_axis1 = tf.concat([tensor1, tensor2], axis=1)
print("Concatenated along axis 1:\n", concat_axis1)

# Stack tensors along a new axis
stacked = tf.stack([tensor1, tensor2], axis=0)
print("Stacked Tensor:\n", stacked)
print("Stacked Shape:", stacked.shape)  # (2, 2, 2)

Concatenated along axis 0:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
Concatenated along axis 1:
 tf.Tensor(
[[1 2 5 6]
 [3 4 7 8]], shape=(2, 4), dtype=int32)
Stacked Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Stacked Shape: (2, 2, 2)


In [18]:
indices = tf.constant([0, 1, 2, 1])
depth = 3
one_hot = tf.one_hot(indices, depth)
print("One-Hot Encoded Tensor:\n", one_hot)

matrix = tf.constant([[1., 2.], [3., 4.]])
inverse = tf.linalg.inv(matrix)
print("Inverse of Matrix:\n", inverse)

matrix = tf.constant([[1., 2.], [3., 4.]])
eigenvalues, eigenvectors = tf.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

One-Hot Encoded Tensor:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]], shape=(4, 3), dtype=float32)
Inverse of Matrix:
 tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
Eigenvalues: tf.Tensor([-0.37228122+0.j  5.372281  +0.j], shape=(2,), dtype=complex64)
Eigenvectors:
 tf.Tensor(
[[-0.8245648 +0.j -0.41597357+0.j]
 [ 0.56576747+0.j -0.90937674+0.j]], shape=(2, 2), dtype=complex64)


In [19]:
import tensorflow as tf

# Creating two tensors
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Arithmetic Operations
addition = a + b
multiplication = a * b
matrix_product = tf.matmul(a, b)

print("Addition:\n", addition)
print("Element-Wise Multiplication:\n", multiplication)
print("Matrix Product:\n", matrix_product)

# Reshaping
reshaped = tf.reshape(a, (4, 1))
print("Reshaped Tensor:\n", reshaped)

# Slicing
sliced = a[:, 1]
print("Sliced Tensor:", sliced)

# Reduction
sum_all = tf.reduce_sum(a)
print("Sum of All Elements:", sum_all)

Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Element-Wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Matrix Product:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Reshaped Tensor:
 tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)
Sliced Tensor: tf.Tensor([2 4], shape=(2,), dtype=int32)
Sum of All Elements: tf.Tensor(10, shape=(), dtype=int32)


# **Computational Graphs**

In [20]:
# static computational graph (TensorFlow 1.x), this code doesn't run in new 2.x version
'''
import tensorflow as tf

# Define the computational graph
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = a + b

# Create a session to run the graph
with tf.Session() as sess:
    result = sess.run(c, feed_dict={a: 2.0, b: 3.0})
    print("Result:", result)  # Output: Result: 5.0
'''

'\nimport tensorflow as tf\n\n# Define the computational graph\na = tf.placeholder(tf.float32)\nb = tf.placeholder(tf.float32)\nc = a + b\n\n# Create a session to run the graph\nwith tf.Session() as sess:\n    result = sess.run(c, feed_dict={a: 2.0, b: 3.0})\n    print("Result:", result)  # Output: Result: 5.0\n'

In [21]:
# static computational graph (TensorFlow 2.x), see this runs

import tensorflow as tf

# Define and execute operations on-the-fly
a = tf.constant(2.0)
b = tf.constant(3.0)
c = a + b
print("Result:", c.numpy())  # Output: Result: 5.0

Result: 5.0


In [22]:
import tensorflow as tf

@tf.function         #decorator used to convert python function into static graph for performance optimization
def add(a, b):
    return a + b

a = tf.constant(2.0)
b = tf.constant(3.0)

# Execute the function  (still providing the flexibility to define and execute functions imperatively)
result = add(a, b)       
print("Result:", result.numpy())  

Result: 5.0


In [23]:
import tensorflow as tf
import numpy as np

# Define a simple sequential model using Input layer
model = tf.keras.Sequential([
    tf.keras.Input(shape=(5,)),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Generate dummy data
X = np.random.rand(100, 5)
y = np.random.rand(100, 1)

# Train the model
model.fit(X, y, epochs=5)

# Make a prediction
prediction = model.predict(np.random.rand(1, 5))
print("Prediction:", prediction)


Epoch 1/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.7166
Epoch 2/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6897 
Epoch 3/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6566 
Epoch 4/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6213 
Epoch 5/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6019 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
Prediction: [[0.08081713]]


# **Core TensorFlow Concepts**

In [24]:
import tensorflow as tf

# Creating a constant tensor
const_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
print("Constant Tensor:", const_tensor)

Constant Tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [25]:
# Creating a variable tensor
var_tensor = tf.Variable([1.0, 2.0, 3.0], dtype=tf.float32)
print("Variable Tensor:", var_tensor)

Variable Tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [26]:
#initialization

# Initializing a variable with zeros
var_zero = tf.Variable(tf.zeros([2, 3]), name='zero_initializer')

# Initializing a variable with random values
var_random = tf.Variable(tf.random.normal([2, 3]), name='random_initializer')

#naming

weight = tf.Variable(tf.random.normal([784, 256]), name='weights')
bias = tf.constant([0.1] * 256, dtype=tf.float32, name='biases')

#scope management

with tf.name_scope('layer1'):
    weights = tf.Variable(tf.random.normal([784, 256]), name='weights')
    biases = tf.constant([0.1] * 256, dtype=tf.float32, name='biases')

#use variables to avoid unnecessary memory usage

In [27]:
#building simple linear regression model using variables and constants

import tensorflow as tf

# Define Constants for input data
X = tf.constant([[1.0], [2.0], [3.0], [4.0]], dtype=tf.float32)  # Input features
Y = tf.constant([[2.0], [4.0], [6.0], [8.0]], dtype=tf.float32)  # Target values

# Define Variables for model parameters (weights and bias)
W = tf.Variable([[0.0]], dtype=tf.float32, name='weight')
b = tf.Variable([0.0], dtype=tf.float32, name='bias')

# Define the linear model
def linear_model(X):
    return tf.matmul(X, W) + b

# Define the loss function (Mean Squared Error)
def loss_fn(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true))

# Define the optimizer
optimizer = tf.optimizers.SGD(learning_rate=0.01)

# Training loop
for epoch in range(1000):
    with tf.GradientTape() as tape:
        y_pred = linear_model(X)
        loss = loss_fn(y_pred, Y)
    
    # Compute gradients
    gradients = tape.gradient(loss, [W, b])
    
    # Update variables
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss = {loss.numpy()}, W = {W.numpy()}, b = {b.numpy()}")

# Final model parameters
print("Trained Weights:", W.numpy())
print("Trained Bias:", b.numpy())

Epoch 0: Loss = 30.0, W = [[0.29999998]], b = [0.09999999]
Epoch 100: Loss = 0.03408462926745415, W = [[1.8468075]], b = [0.45040485]
Epoch 200: Loss = 0.01871202513575554, W = [[1.8864939]], b = [0.33372158]
Epoch 300: Loss = 0.010272667743265629, W = [[1.9158992]], b = [0.24726659]
Epoch 400: Loss = 0.005639577750116587, W = [[1.9376867]], b = [0.18320896]
Epoch 500: Loss = 0.0030960547737777233, W = [[1.9538298]], b = [0.13574634]
Epoch 600: Loss = 0.001699708285741508, W = [[1.9657906]], b = [0.10057957]
Epoch 700: Loss = 0.0009331251494586468, W = [[1.974653]], b = [0.0745233]
Epoch 800: Loss = 0.0005122720031067729, W = [[1.9812194]], b = [0.05521719]
Epoch 900: Loss = 0.00028123249649070203, W = [[1.9860847]], b = [0.04091255]
Trained Weights: [[1.9896587]]
Trained Bias: [0.03040474]
